### ISSUE TITLE
Duplicate Mod Error (On Server, no error on single player)

### ISSUE THREAD

**Issue by Naigaru** [jingshenSN2/CraftTime#2]
Minecraft Version 1.12.2
Mod Version 0.3.2

[crash-2021-02-12_16.11.13-server.txt](https://github.com/jingshenSN2/CraftTime/files/5969510/crash-2021-02-12_16.11.13-server.txt)

**Comment by jingshenSN2** [comment]
Please try 0.3.3~

**Comment by jingshenSN2** [comment]
Try 0.3.4, should work on the server.

**Comment by Naigaru** [comment]
Hi there, thank you for the quick reply.
This error seems to be fixed now, however there is a new error showing up w
hen a player joins the server (so not an error on the server, but on the client)
Here is the error log for that if you would like to look into that. Thank you :3
[latest.log](https://github.com/jingshenSN2/CraftTime/files/5973873/latest.log)

**Comment by jingshenSN2** [comment]
Try 0.4.1. (after 2 hours of debugging, i found that the bug is just caused by a too-long network channel name...)

**Comment by Naigaru** [comment]
Okie all up and working, thanks for all the hard work :3 (and sorry ;-; lol, bugs be evil)
