### ISSUE TITLE
cant change speed multiplier

### ISSUE THREAD

**Issue by RyanCR03** [jingshenSN2/CraftTime#6]
i changed both the global and mod multiplier in the craft_time config and craft_time_sample config but craft_time_sample keeps resetting and it also isn't changing the speed.

**Comment by jingshenSN2** [comment]
1. craft_time_sample.json is only a SAMPLE and will regenerate every time you join the game. it won't affect the game.
2. multipliers should work. Maybe you didn't notice the formula is 20 + global_multiplier * XXXX, so there will be fixed 20 ticks craft time.

**Comment by RyanCR03** [comment]
oh so is there a way I can make it faster because I don't like how crafting a ladder takes like two hours. i wanted the speed of the crafting to be comparable to crafting in ssbu

**Comment by jingshenSN2** [comment]
currently, besides multipliers, the only way to speed up is to gain a higher player exp level or add Project MMO mod. You will get 2%speed-up per exp level and 5%speed-up per crafting level in PMMO. maybe i will change the formula in the next version.

**Comment by jingshenSN2** [comment]
maybe you can tell me which MC version and mod loader you are using? so I can make a quick release for that version.

**Comment by RyanCR03** [comment]
fabric 1.16.4
